name: meogo-main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      FCM_URL: ${{ secrets.FCM_URL }}
      CAREER_URL: ${{ secrets.CAREER_URL }}
      CAREER_KEY: ${{ secrets.CAREER_KEY }}
      ACCESS_EXP: ${{ secrets.ACCESS_EXP }}
      REFRESH_EXP: ${{ secrets.REFRESH_EXP }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            clean build
            --no-daemon

      - name: Run tests with verbose output
        run: ./gradlew test --debug
